name: apprunnertest
services:
- name: server
  source_dir: /
  github:
    repo: mdazamdevops/apprunnertest
    branch: main
  run_command: npm run start
  build_command: npm run install:all && npm run build:all
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  environment_variables:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5000"
  - key: NPM_CONFIG_LEGACY_PEER_DEPS
    value: "true"
