name: apprunnertest
services:
- name: server
  source_dir: /
  github:
    repo: mdazamdevops/apprunnertest
    branch: main
  run_command: cd server && npm start
  build_command: |
    npm install --legacy-peer-deps
    cd server && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  environment_variables:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5000"
