name: apprunnertest
services:
- name: server
  source_dir: /server
  github:
    repo: mdazamdevops/apprunnertest
    branch: main
  run_command: npm start
  build_command: |
    npm install --legacy-peer-deps
    npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  environment_variables:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5000"
  - key: CLIENT_ORIGIN
    value: "https://your-app.ondigitalocean.app"
  - key: NPM_CONFIG_LEGACY_PEER_DEPS
    value: "true"
