name: apprunnertest
services:
- name: server
  github:
    repo: mdazamdevops/apprunnertest
    branch: main
  source_dir: /
  build_command: npm install --legacy-peer-deps && npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: NPM_CONFIG_LEGACY_PEER_DEPS
    value: "true"
